// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvQ4L8xYgKl9eL_jVe8ZOGg1zRKrVBxU',
    appId: '1:794315754414:web:30e2eb5b8a0777f050963f',
    messagingSenderId: '794315754414',
    projectId: 'barcode-price-scanner',
    authDomain: 'barcode-price-scanner.firebaseapp.com',
    storageBucket: 'barcode-price-scanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkPIH918G-3HVWFG4vzohp4iiiG_rGnA',
    appId: '1:794315754414:android:4c02ff097bf5480550963f',
    messagingSenderId: '794315754414',
    projectId: 'barcode-price-scanner',
    storageBucket: 'barcode-price-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YMC_d89KGLFyWlDbAnMYiwo-4_lVxzA', // Aynı kalmış
    appId:
        '1:794315754414:ios:c1c80fc7f0ba476450963f', // BU DEĞİŞTİ (Yeni Plist'ten aldım)
    messagingSenderId: '794315754414',
    projectId: 'barcode-price-scanner',
    storageBucket: 'barcode-price-scanner.firebasestorage.app',
    iosBundleId: 'com.bekirmese.scanwiser', // BU DEĞİŞTİ (Yeni isminiz)
  );
}